/**
 * PROJECT IMAGES — static, committed, and self-sufficient.
 * ---------------------------------------------------------------------------
 * Every path below points at a real file committed under
 * public/images/projects/. Nothing regenerates this at build time, so a
 * deploy can never wipe it.
 *
 * Produced by scripts/build-project-images.mjs. To add or replace photos, run
 * `npm run build:images -- "/path/to/Projects"` locally and commit the result,
 * or drop files into public/images/projects/<folder>/ and add the entry here
 * by hand — width and height must match the real file to avoid layout shift.
 */

export type ProjectImageRef = { src: string; alt: string; width: number; height: number };
export type ProjectVideoRef = {
  src: string;
  poster: string;
  title: string;
  kind: 'walkthrough' | 'before-after' | 'application' | 'crew' | 'overview';
  orientation: 'portrait' | 'landscape';
  width: number;
  height: number;
  duration?: number;
};
export type ProjectImageSet = {
  folder: string;
  hero?: ProjectImageRef;
  gallery: ProjectImageRef[];
  videos?: ProjectVideoRef[];
};
export type DiscoveredProject = { slug: string; name: string; industry: string; location?: string; art: string };

/** Photography keyed by project slug. */
export const projectImages: Record<string, ProjectImageSet> = {
  'aldi': {
    folder: 'aldi-kansas-city',
    hero: { src: '/images/projects/aldi-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at Aldi, Kansas City', width: 960, height: 720 },
    gallery: [
      { src: '/images/projects/aldi-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at Aldi, Kansas City — photo 2', width: 960, height: 720 },
      { src: '/images/projects/aldi-kansas-city/02.jpg', alt: 'Painting work by Childress Painting at Aldi, Kansas City — photo 3', width: 960, height: 720 },
      { src: '/images/projects/aldi-kansas-city/03.jpg', alt: 'Painting work by Childress Painting at Aldi, Kansas City — photo 4', width: 960, height: 720 },
      { src: '/images/projects/aldi-kansas-city/04.jpg', alt: 'Painting work by Childress Painting at Aldi, Kansas City — photo 5', width: 960, height: 720 },
    ],
  },
  'billy-goat-industries': {
    folder: 'billy-goat-industries-lee-summit',
    hero: { src: '/images/projects/billy-goat-industries-lee-summit/hero.jpg', alt: 'Painting work by Childress Painting at Billy Goat Industries, Lee Summit', width: 864, height: 737 },
    gallery: [
      { src: '/images/projects/billy-goat-industries-lee-summit/01.jpg', alt: 'Painting work by Childress Painting at Billy Goat Industries, Lee Summit — photo 2', width: 1800, height: 2400 },
      { src: '/images/projects/billy-goat-industries-lee-summit/02.jpg', alt: 'Painting work by Childress Painting at Billy Goat Industries, Lee Summit — photo 3', width: 1800, height: 2400 },
      { src: '/images/projects/billy-goat-industries-lee-summit/03.jpg', alt: 'Painting work by Childress Painting at Billy Goat Industries, Lee Summit — photo 4', width: 1800, height: 2400 },
      { src: '/images/projects/billy-goat-industries-lee-summit/04.jpg', alt: 'Painting work by Childress Painting at Billy Goat Industries, Lee Summit — photo 5', width: 1800, height: 2400 },
      { src: '/images/projects/billy-goat-industries-lee-summit/05.jpg', alt: 'Painting work by Childress Painting at Billy Goat Industries, Lee Summit — photo 6', width: 1800, height: 2400 },
      { src: '/images/projects/billy-goat-industries-lee-summit/06.jpg', alt: 'Painting work by Childress Painting at Billy Goat Industries, Lee Summit — photo 7', width: 1800, height: 2400 },
      { src: '/images/projects/billy-goat-industries-lee-summit/07.jpg', alt: 'Painting work by Childress Painting at Billy Goat Industries, Lee Summit — photo 8', width: 1800, height: 2400 },
    ],
    videos: [
      {
        src: '/videos/projects/billy-goat-industries-lee-summit/clip-01.mp4',
        poster: '/videos/projects/billy-goat-industries-lee-summit/clip-01.jpg',
        title: 'Childress Painting on site at Billy Goat Industries, Lee Summit',
        kind: 'walkthrough',
        orientation: 'portrait',
        width: 720, height: 1280, duration: 4,
      },
      {
        src: '/videos/projects/billy-goat-industries-lee-summit/clip-02.mp4',
        poster: '/videos/projects/billy-goat-industries-lee-summit/clip-02.jpg',
        title: 'Childress Painting on site at Billy Goat Industries, Lee Summit',
        kind: 'walkthrough',
        orientation: 'portrait',
        width: 720, height: 1280, duration: 33,
      },
    ],
  },
  'brookshire-renovation': {
    folder: 'brookshire-renovation-kansas-city',
    hero: { src: '/images/projects/brookshire-renovation-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at Brookshire Renovation, Kansas City', width: 1950, height: 2600 },
    gallery: [
      { src: '/images/projects/brookshire-renovation-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at Brookshire Renovation, Kansas City — photo 2', width: 1800, height: 2400 },
      { src: '/images/projects/brookshire-renovation-kansas-city/02.jpg', alt: 'Painting work by Childress Painting at Brookshire Renovation, Kansas City — photo 3', width: 1800, height: 2400 },
      { src: '/images/projects/brookshire-renovation-kansas-city/03.jpg', alt: 'Painting work by Childress Painting at Brookshire Renovation, Kansas City — photo 4', width: 1800, height: 2400 },
      { src: '/images/projects/brookshire-renovation-kansas-city/04.jpg', alt: 'Painting work by Childress Painting at Brookshire Renovation, Kansas City — photo 5', width: 1800, height: 2400 },
      { src: '/images/projects/brookshire-renovation-kansas-city/05.jpg', alt: 'Painting work by Childress Painting at Brookshire Renovation, Kansas City — photo 6', width: 1800, height: 2400 },
      { src: '/images/projects/brookshire-renovation-kansas-city/06.jpg', alt: 'Painting work by Childress Painting at Brookshire Renovation, Kansas City — photo 7', width: 1800, height: 2400 },
      { src: '/images/projects/brookshire-renovation-kansas-city/07.jpg', alt: 'Painting work by Childress Painting at Brookshire Renovation, Kansas City — photo 8', width: 1800, height: 2400 },
    ],
  },
  'custom-wood-staining-residential-home': {
    folder: 'custom-wood-staining-overland-park',
    hero: { src: '/images/projects/custom-wood-staining-overland-park/hero.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park', width: 680, height: 510 },
    gallery: [
      { src: '/images/projects/custom-wood-staining-overland-park/01.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 2', width: 680, height: 426 },
      { src: '/images/projects/custom-wood-staining-overland-park/02.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 3', width: 680, height: 382 },
      { src: '/images/projects/custom-wood-staining-overland-park/03.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 4', width: 680, height: 382 },
      { src: '/images/projects/custom-wood-staining-overland-park/04.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 5', width: 680, height: 510 },
      { src: '/images/projects/custom-wood-staining-overland-park/05.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 6', width: 680, height: 510 },
      { src: '/images/projects/custom-wood-staining-overland-park/06.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 7', width: 680, height: 510 },
      { src: '/images/projects/custom-wood-staining-overland-park/07.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 8', width: 680, height: 382 },
      { src: '/images/projects/custom-wood-staining-overland-park/08.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 9', width: 680, height: 510 },
      { src: '/images/projects/custom-wood-staining-overland-park/09.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 10', width: 680, height: 380 },
      { src: '/images/projects/custom-wood-staining-overland-park/10.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 11', width: 680, height: 510 },
      { src: '/images/projects/custom-wood-staining-overland-park/11.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 12', width: 680, height: 261 },
      { src: '/images/projects/custom-wood-staining-overland-park/12.jpg', alt: 'Painting work by Childress Painting at Custom Wood Staining (Residential Home), Overland Park — photo 13', width: 680, height: 382 },
    ],
  },
  'evan-talon-custom-homes': {
    folder: 'evan-talon-custom-homes-overland-park',
    hero: { src: '/images/projects/evan-talon-custom-homes-overland-park/hero.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park', width: 1080, height: 552 },
    gallery: [
      { src: '/images/projects/evan-talon-custom-homes-overland-park/01.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 2', width: 964, height: 642 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/02.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 3', width: 966, height: 640 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/03.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 4', width: 814, height: 644 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/04.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 5', width: 1118, height: 644 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/05.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 6', width: 958, height: 642 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/06.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 7', width: 972, height: 574 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/07.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 8', width: 974, height: 696 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/08.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 9', width: 958, height: 630 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/09.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 10', width: 958, height: 590 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/10.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 11', width: 974, height: 588 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/11.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 12', width: 1090, height: 608 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/12.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 13', width: 842, height: 756 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/13.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 14', width: 1090, height: 726 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/14.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 15', width: 840, height: 582 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/15.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 16', width: 580, height: 812 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/16.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 17', width: 788, height: 524 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/17.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 18', width: 516, height: 646 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/18.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 19', width: 788, height: 574 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/19.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 20', width: 514, height: 726 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/20.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 21', width: 580, height: 1010 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/21.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 22', width: 788, height: 668 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/22.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 23', width: 514, height: 812 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/23.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 24', width: 1416, height: 862 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/24.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 25', width: 516, height: 500 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/25.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 26', width: 1010, height: 604 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/26.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 27', width: 922, height: 602 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/27.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 28', width: 852, height: 540 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/28.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 29', width: 1080, height: 684 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/29.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 30', width: 854, height: 568 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/30.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 31', width: 1080, height: 720 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/31.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 32', width: 854, height: 540 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/32.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 33', width: 1080, height: 642 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/33.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 34', width: 608, height: 812 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/34.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 35', width: 460, height: 814 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/35.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 36', width: 814, height: 540 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/36.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 37', width: 814, height: 488 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/37.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 38', width: 610, height: 540 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/38.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 39', width: 460, height: 812 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/39.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 40', width: 814, height: 542 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/40.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 41', width: 608, height: 406 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/41.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 42', width: 812, height: 540 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/42.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 43', width: 464, height: 842 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/43.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 44', width: 812, height: 540 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/44.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 45', width: 464, height: 918 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/45.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 46', width: 608, height: 766 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/46.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 47', width: 812, height: 630 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/47.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 48', width: 1036, height: 612 },
      { src: '/images/projects/evan-talon-custom-homes-overland-park/48.jpg', alt: 'Painting work by Childress Painting at Evan Talon Custom Homes, Overland Park — photo 49', width: 894, height: 612 },
    ],
  },
  'freddys-frozen-custard': {
    folder: 'freddys-frozen-custard-kansas-city',
    hero: { src: '/images/projects/freddys-frozen-custard-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at Freddy\'s Frozen Custad & Steakburgers, Kansas City', width: 720, height: 960 },
    gallery: [
      { src: '/images/projects/freddys-frozen-custard-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at Freddy\'s Frozen Custad & Steakburgers, Kansas City — photo 2', width: 720, height: 960 },
      { src: '/images/projects/freddys-frozen-custard-kansas-city/02.jpg', alt: 'Painting work by Childress Painting at Freddy\'s Frozen Custad & Steakburgers, Kansas City — photo 3', width: 540, height: 960 },
    ],
  },
  'gordon-ramsay-steakhouse': {
    folder: 'gordon-ramsay-steakhouse-kansas-city',
    hero: { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City', width: 960, height: 866 },
    gallery: [
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 2', width: 960, height: 720 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/02.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 3', width: 960, height: 720 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/03.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 4', width: 960, height: 720 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/04.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 5', width: 960, height: 720 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/05.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 6', width: 720, height: 960 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/06.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 7', width: 960, height: 720 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/07.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 8', width: 746, height: 960 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/08.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 9', width: 960, height: 720 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/09.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 10', width: 960, height: 720 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/10.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 11', width: 960, height: 720 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/11.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 12', width: 960, height: 720 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/12.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 13', width: 560, height: 960 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/13.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 14', width: 720, height: 960 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/14.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 15', width: 720, height: 960 },
      { src: '/images/projects/gordon-ramsay-steakhouse-kansas-city/15.jpg', alt: 'Painting work by Childress Painting at Gordon Ramsay\'s Steakhouse, Kansas City — photo 16', width: 960, height: 906 },
    ],
  },
  'gould-evans': {
    folder: 'gould-evans-kansas-city',
    hero: { src: '/images/projects/gould-evans-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City', width: 900, height: 506 },
    gallery: [
      { src: '/images/projects/gould-evans-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 2', width: 900, height: 508 },
      { src: '/images/projects/gould-evans-kansas-city/02.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 3', width: 900, height: 506 },
      { src: '/images/projects/gould-evans-kansas-city/03.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 4', width: 900, height: 506 },
      { src: '/images/projects/gould-evans-kansas-city/04.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 5', width: 900, height: 506 },
      { src: '/images/projects/gould-evans-kansas-city/05.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 6', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/06.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 7', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/07.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 8', width: 900, height: 508 },
      { src: '/images/projects/gould-evans-kansas-city/08.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 9', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/09.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 10', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/10.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 11', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/11.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 12', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/12.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 13', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/13.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 14', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/14.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 15', width: 900, height: 508 },
      { src: '/images/projects/gould-evans-kansas-city/15.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 16', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/16.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 17', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/17.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 18', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/18.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 19', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/19.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 20', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/20.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 21', width: 900, height: 508 },
      { src: '/images/projects/gould-evans-kansas-city/21.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 22', width: 900, height: 506 },
      { src: '/images/projects/gould-evans-kansas-city/22.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 23', width: 900, height: 507 },
      { src: '/images/projects/gould-evans-kansas-city/23.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 24', width: 900, height: 506 },
      { src: '/images/projects/gould-evans-kansas-city/24.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 25', width: 900, height: 508 },
      { src: '/images/projects/gould-evans-kansas-city/25.jpg', alt: 'Painting work by Childress Painting at Gould Evans, Kansas City — photo 26', width: 900, height: 506 },
    ],
  },
  'health-and-beauty-tech': {
    folder: 'health-and-beauty-tech-kansas-city-airport',
    hero: { src: '/images/projects/health-and-beauty-tech-kansas-city-airport/hero.jpg', alt: 'Painting work by Childress Painting at Health & Beauty Tech, Kansas City Airport', width: 2400, height: 1800 },
    gallery: [
      { src: '/images/projects/health-and-beauty-tech-kansas-city-airport/01.jpg', alt: 'Painting work by Childress Painting at Health & Beauty Tech, Kansas City Airport — photo 2', width: 1800, height: 2400 },
      { src: '/images/projects/health-and-beauty-tech-kansas-city-airport/02.jpg', alt: 'Painting work by Childress Painting at Health & Beauty Tech, Kansas City Airport — photo 3', width: 1800, height: 2400 },
      { src: '/images/projects/health-and-beauty-tech-kansas-city-airport/03.jpg', alt: 'Painting work by Childress Painting at Health & Beauty Tech, Kansas City Airport — photo 4', width: 1800, height: 2400 },
      { src: '/images/projects/health-and-beauty-tech-kansas-city-airport/04.jpg', alt: 'Painting work by Childress Painting at Health & Beauty Tech, Kansas City Airport — photo 5', width: 1800, height: 2400 },
    ],
  },
  'kcfd-fire-station-15': {
    folder: 'kcfd-fire-station-15-kansas-city',
    hero: { src: '/images/projects/kcfd-fire-station-15-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at KCFD Fire Station 15, Kansas City', width: 960, height: 720 },
    gallery: [
      { src: '/images/projects/kcfd-fire-station-15-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at KCFD Fire Station 15, Kansas City — photo 2', width: 960, height: 480 },
      { src: '/images/projects/kcfd-fire-station-15-kansas-city/02.jpg', alt: 'Painting work by Childress Painting at KCFD Fire Station 15, Kansas City — photo 3', width: 960, height: 630 },
      { src: '/images/projects/kcfd-fire-station-15-kansas-city/03.jpg', alt: 'Painting work by Childress Painting at KCFD Fire Station 15, Kansas City — photo 4', width: 960, height: 720 },
      { src: '/images/projects/kcfd-fire-station-15-kansas-city/04.jpg', alt: 'Painting work by Childress Painting at KCFD Fire Station 15, Kansas City — photo 5', width: 960, height: 610 },
      { src: '/images/projects/kcfd-fire-station-15-kansas-city/05.jpg', alt: 'Painting work by Childress Painting at KCFD Fire Station 15, Kansas City — photo 6', width: 960, height: 718 },
      { src: '/images/projects/kcfd-fire-station-15-kansas-city/06.jpg', alt: 'Painting work by Childress Painting at KCFD Fire Station 15, Kansas City — photo 7', width: 750, height: 498 },
      { src: '/images/projects/kcfd-fire-station-15-kansas-city/07.jpg', alt: 'Painting work by Childress Painting at KCFD Fire Station 15, Kansas City — photo 8', width: 960, height: 720 },
    ],
  },
  'mckeevers': {
    folder: 'mckeevers-kansas-city',
    hero: { src: '/images/projects/mckeevers-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City', width: 960, height: 792 },
    gallery: [
      { src: '/images/projects/mckeevers-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 2', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/02.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 3', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/03.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 4', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/04.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 5', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/05.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 6', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/06.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 7', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/07.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 8', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/08.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 9', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/09.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 10', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/10.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 11', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/11.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 12', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/12.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 13', width: 960, height: 582 },
      { src: '/images/projects/mckeevers-kansas-city/13.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 14', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/14.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 15', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/15.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 16', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/16.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 17', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/17.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 18', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/18.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 19', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/19.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 20', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/20.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 21', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/21.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 22', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/22.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 23', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/23.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 24', width: 540, height: 960 },
      { src: '/images/projects/mckeevers-kansas-city/24.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 25', width: 950, height: 960 },
      { src: '/images/projects/mckeevers-kansas-city/25.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 26', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/26.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 27', width: 960, height: 634 },
      { src: '/images/projects/mckeevers-kansas-city/27.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 28', width: 960, height: 720 },
      { src: '/images/projects/mckeevers-kansas-city/28.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 29', width: 720, height: 960 },
      { src: '/images/projects/mckeevers-kansas-city/29.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 30', width: 720, height: 960 },
      { src: '/images/projects/mckeevers-kansas-city/30.jpg', alt: 'Painting work by Childress Painting at Mckeevers, Kansas City — photo 31', width: 720, height: 960 },
    ],
  },
  'meadowbrook-animal-hospital': {
    folder: 'meadowbrook-animal-hospital-kansas-city',
    hero: { src: '/images/projects/meadowbrook-animal-hospital-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at Meadowbrook Animal Hospital, Kansas City', width: 1950, height: 2600 },
    gallery: [
      { src: '/images/projects/meadowbrook-animal-hospital-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at Meadowbrook Animal Hospital, Kansas City — photo 2', width: 1800, height: 2400 },
    ],
    videos: [
      {
        src: '/videos/projects/meadowbrook-animal-hospital-kansas-city/clip-01.mp4',
        poster: '/videos/projects/meadowbrook-animal-hospital-kansas-city/clip-01.jpg',
        title: 'Childress Painting on site at Meadowbrook Animal Hospital, Kansas City',
        kind: 'walkthrough',
        orientation: 'portrait',
        width: 720, height: 1280, duration: 10,
      },
    ],
  },
  'phillips-66': {
    folder: 'phillips-66-kansas-city',
    hero: { src: '/images/projects/phillips-66-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at Phillips 66, Kansas City', width: 960, height: 720 },
    gallery: [
      { src: '/images/projects/phillips-66-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at Phillips 66, Kansas City — photo 2', width: 960, height: 720 },
    ],
  },
  'shawnee-town-government-buildings': {
    folder: 'shawnee-town-government-buildings-shawnee',
    hero: { src: '/images/projects/shawnee-town-government-buildings-shawnee/hero.jpg', alt: 'Painting work by Childress Painting at Shawnee Town Government Buildings, Shawnee', width: 960, height: 720 },
    gallery: [
      { src: '/images/projects/shawnee-town-government-buildings-shawnee/01.jpg', alt: 'Painting work by Childress Painting at Shawnee Town Government Buildings, Shawnee — photo 2', width: 720, height: 960 },
      { src: '/images/projects/shawnee-town-government-buildings-shawnee/02.jpg', alt: 'Painting work by Childress Painting at Shawnee Town Government Buildings, Shawnee — photo 3', width: 720, height: 960 },
      { src: '/images/projects/shawnee-town-government-buildings-shawnee/03.jpg', alt: 'Painting work by Childress Painting at Shawnee Town Government Buildings, Shawnee — photo 4', width: 960, height: 720 },
      { src: '/images/projects/shawnee-town-government-buildings-shawnee/04.jpg', alt: 'Painting work by Childress Painting at Shawnee Town Government Buildings, Shawnee — photo 5', width: 960, height: 720 },
      { src: '/images/projects/shawnee-town-government-buildings-shawnee/05.jpg', alt: 'Painting work by Childress Painting at Shawnee Town Government Buildings, Shawnee — photo 6', width: 750, height: 562 },
    ],
  },
  'stop-n-shop': {
    folder: 'stop-n-shop-kansas-city',
    hero: { src: '/images/projects/stop-n-shop-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at Stop N Shop, Kansas City', width: 960, height: 720 },
    gallery: [
      { src: '/images/projects/stop-n-shop-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at Stop N Shop, Kansas City — photo 2', width: 960, height: 720 },
      { src: '/images/projects/stop-n-shop-kansas-city/02.jpg', alt: 'Painting work by Childress Painting at Stop N Shop, Kansas City — photo 3', width: 960, height: 720 },
      { src: '/images/projects/stop-n-shop-kansas-city/03.jpg', alt: 'Painting work by Childress Painting at Stop N Shop, Kansas City — photo 4', width: 960, height: 720 },
      { src: '/images/projects/stop-n-shop-kansas-city/04.jpg', alt: 'Painting work by Childress Painting at Stop N Shop, Kansas City — photo 5', width: 960, height: 720 },
      { src: '/images/projects/stop-n-shop-kansas-city/05.jpg', alt: 'Painting work by Childress Painting at Stop N Shop, Kansas City — photo 6', width: 960, height: 720 },
      { src: '/images/projects/stop-n-shop-kansas-city/06.jpg', alt: 'Painting work by Childress Painting at Stop N Shop, Kansas City — photo 7', width: 960, height: 720 },
    ],
  },
  'torchys-tacos': {
    folder: 'torchys-tacos-kansas-city',
    hero: { src: '/images/projects/torchys-tacos-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at Torchy\'s Tacos, Kansas City', width: 960, height: 720 },
    gallery: [
      { src: '/images/projects/torchys-tacos-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at Torchy\'s Tacos, Kansas City — photo 2', width: 720, height: 960 },
      { src: '/images/projects/torchys-tacos-kansas-city/02.jpg', alt: 'Painting work by Childress Painting at Torchy\'s Tacos, Kansas City — photo 3', width: 960, height: 720 },
      { src: '/images/projects/torchys-tacos-kansas-city/03.jpg', alt: 'Painting work by Childress Painting at Torchy\'s Tacos, Kansas City — photo 4', width: 960, height: 720 },
      { src: '/images/projects/torchys-tacos-kansas-city/04.jpg', alt: 'Painting work by Childress Painting at Torchy\'s Tacos, Kansas City — photo 5', width: 960, height: 720 },
      { src: '/images/projects/torchys-tacos-kansas-city/05.jpg', alt: 'Painting work by Childress Painting at Torchy\'s Tacos, Kansas City — photo 6', width: 960, height: 720 },
      { src: '/images/projects/torchys-tacos-kansas-city/06.jpg', alt: 'Painting work by Childress Painting at Torchy\'s Tacos, Kansas City — photo 7', width: 960, height: 720 },
      { src: '/images/projects/torchys-tacos-kansas-city/07.jpg', alt: 'Painting work by Childress Painting at Torchy\'s Tacos, Kansas City — photo 8', width: 720, height: 960 },
    ],
  },
  'union-event-venue': {
    folder: 'union-event-venue-kansas-city',
    hero: { src: '/images/projects/union-event-venue-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at Union Event Venue, Kansas City', width: 960, height: 720 },
    gallery: [
      { src: '/images/projects/union-event-venue-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at Union Event Venue, Kansas City — photo 2', width: 750, height: 562 },
      { src: '/images/projects/union-event-venue-kansas-city/02.jpg', alt: 'Painting work by Childress Painting at Union Event Venue, Kansas City — photo 3', width: 960, height: 720 },
    ],
  },
  'us-army-reserve': {
    folder: 'us-army-reserve-kansas-city',
    hero: { src: '/images/projects/us-army-reserve-kansas-city/hero.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City', width: 2400, height: 1800 },
    gallery: [
      { src: '/images/projects/us-army-reserve-kansas-city/01.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 2', width: 1320, height: 2868 },
      { src: '/images/projects/us-army-reserve-kansas-city/02.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 3', width: 1800, height: 1350 },
      { src: '/images/projects/us-army-reserve-kansas-city/03.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 4', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/04.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 5', width: 1800, height: 1350 },
      { src: '/images/projects/us-army-reserve-kansas-city/05.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 6', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/06.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 7', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/07.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 8', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/08.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 9', width: 1800, height: 1350 },
      { src: '/images/projects/us-army-reserve-kansas-city/09.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 10', width: 1800, height: 1350 },
      { src: '/images/projects/us-army-reserve-kansas-city/10.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 11', width: 1800, height: 1350 },
      { src: '/images/projects/us-army-reserve-kansas-city/11.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 12', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/12.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 13', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/13.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 14', width: 1800, height: 1350 },
      { src: '/images/projects/us-army-reserve-kansas-city/14.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 15', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/15.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 16', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/16.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 17', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/17.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 18', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/18.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 19', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/19.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 20', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/20.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 21', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/21.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 22', width: 1800, height: 1350 },
      { src: '/images/projects/us-army-reserve-kansas-city/22.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 23', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/23.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 24', width: 1800, height: 2400 },
      { src: '/images/projects/us-army-reserve-kansas-city/24.jpg', alt: 'Painting work by Childress Painting at US Army Reserve, Kansas City — photo 25', width: 1800, height: 2400 },
    ],
    videos: [
      {
        src: '/videos/projects/us-army-reserve-kansas-city/clip-01.mp4',
        poster: '/videos/projects/us-army-reserve-kansas-city/clip-01.jpg',
        title: 'Childress Painting on site at US Army Reserve, Kansas City',
        kind: 'walkthrough',
        orientation: 'portrait',
        width: 720, height: 1280, duration: 18,
      },
      {
        src: '/videos/projects/us-army-reserve-kansas-city/clip-02.mp4',
        poster: '/videos/projects/us-army-reserve-kansas-city/clip-02.jpg',
        title: 'Childress Painting on site at US Army Reserve, Kansas City',
        kind: 'walkthrough',
        orientation: 'portrait',
        width: 720, height: 1280, duration: 6,
      },
      {
        src: '/videos/projects/us-army-reserve-kansas-city/clip-03.mp4',
        poster: '/videos/projects/us-army-reserve-kansas-city/clip-03.jpg',
        title: 'Childress Painting on site at US Army Reserve, Kansas City',
        kind: 'walkthrough',
        orientation: 'portrait',
        width: 720, height: 1280, duration: 13,
      },
    ],
  },
};

/** Folders that matched no existing project, added as new projects. */
export const discoveredProjects: DiscoveredProject[] = [
  {
    slug: 'billy-goat-industries',
    name: 'Billy Goat Industries',
    industry: 'retail',
    location: 'Lee Summit',
    art: 'retail',
  },
  {
    slug: 'billy-goat-industries',
    name: 'Billy Goat Industries',
    industry: 'retail',
    location: 'Lee Summit',
    art: 'retail',
  },
  {
    slug: 'brookshire-renovation',
    name: 'Brookshire Renovation',
    industry: 'retail',
    location: 'Kansas City',
    art: 'retail',
  },
  {
    slug: 'brookshire-renovation',
    name: 'Brookshire Renovation',
    industry: 'retail',
    location: 'Kansas City',
    art: 'retail',
  },
  {
    slug: 'custom-wood-staining-residential-home',
    name: 'Custom Wood Staining (Residential Home)',
    industry: 'residential',
    location: 'Overland Park',
    art: 'interior',
  },
  {
    slug: 'custom-wood-staining-residential-home',
    name: 'Custom Wood Staining (Residential Home)',
    industry: 'residential',
    location: 'Overland Park',
    art: 'interior',
  },
  {
    slug: 'evan-talon-custom-homes',
    name: 'Evan Talon Custom Homes',
    industry: 'residential',
    location: 'Overland Park',
    art: 'interior',
  },
  {
    slug: 'evan-talon-custom-homes',
    name: 'Evan Talon Custom Homes',
    industry: 'residential',
    location: 'Overland Park',
    art: 'interior',
  },
  {
    slug: 'gould-evans',
    name: 'Gould Evans',
    industry: 'retail',
    location: 'Kansas City',
    art: 'retail',
  },
  {
    slug: 'gould-evans',
    name: 'Gould Evans',
    industry: 'retail',
    location: 'Kansas City',
    art: 'retail',
  },
  {
    slug: 'health-and-beauty-tech',
    name: 'Health & Beauty Tech',
    industry: 'healthcare',
    location: 'Kansas City Airport',
    art: 'healthcare',
  },
  {
    slug: 'health-and-beauty-tech',
    name: 'Health & Beauty Tech',
    industry: 'healthcare',
    location: 'Kansas City Airport',
    art: 'healthcare',
  },
  {
    slug: 'kcfd-fire-station-15',
    name: 'KCFD Fire Station 15',
    industry: 'government',
    location: 'Kansas City',
    art: 'government',
  },
  {
    slug: 'kcfd-fire-station-15',
    name: 'KCFD Fire Station 15',
    industry: 'government',
    location: 'Kansas City',
    art: 'government',
  },
  {
    slug: 'mckeevers',
    name: 'Mckeevers',
    industry: 'retail',
    location: 'Kansas City',
    art: 'retail',
  },
  {
    slug: 'mckeevers',
    name: 'Mckeevers',
    industry: 'retail',
    location: 'Kansas City',
    art: 'retail',
  },
  {
    slug: 'meadowbrook-animal-hospital',
    name: 'Meadowbrook Animal Hospital',
    industry: 'healthcare',
    location: 'Kansas City',
    art: 'healthcare',
  },
  {
    slug: 'meadowbrook-animal-hospital',
    name: 'Meadowbrook Animal Hospital',
    industry: 'healthcare',
    location: 'Kansas City',
    art: 'healthcare',
  },
  {
    slug: 'shawnee-town-government-buildings',
    name: 'Shawnee Town Government Buildings',
    industry: 'government',
    location: 'Shawnee',
    art: 'government',
  },
  {
    slug: 'shawnee-town-government-buildings',
    name: 'Shawnee Town Government Buildings',
    industry: 'government',
    location: 'Shawnee',
    art: 'government',
  },
  {
    slug: 'stop-n-shop',
    name: 'Stop N Shop',
    industry: 'retail',
    location: 'Kansas City',
    art: 'retail',
  },
  {
    slug: 'stop-n-shop',
    name: 'Stop N Shop',
    industry: 'retail',
    location: 'Kansas City',
    art: 'retail',
  },
  {
    slug: 'union-event-venue',
    name: 'Union Event Venue',
    industry: 'sports-entertainment',
    location: 'Kansas City',
    art: 'sports',
  },
  {
    slug: 'union-event-venue',
    name: 'Union Event Venue',
    industry: 'sports-entertainment',
    location: 'Kansas City',
    art: 'sports',
  },
  {
    slug: 'us-army-reserve',
    name: 'US Army Reserve',
    industry: 'retail',
    location: 'Kansas City',
    art: 'retail',
  },
];
